theme = "cleargruv"

[editor]
auto-completion = false
auto-info = true
line-number = "relative"
color-modes = true
bufferline = "multiple"
shell = ["zsh", "-c"]
# scrolloff = 10
gutters = ["diff", "diagnostics", "line-numbers", "spacer", "spacer"]
cursorline = false
popup-border = "all"
rulers = []

[editor.lsp]
enable = false

[editor.file-picker]
hidden = false

[editor.statusline]
left = [
  "mode", 
  "separator",
  "file-name",
  "spinner"
]
center = [
  # "separator",
  # "spacer",
  "version-control",
  # "spacer",
  # "separator",
  "read-only-indicator",
  "diagnostics"
]
right = [
  "register",
  "separator",
  "selections",
  "separator",
  "position",
  "separator",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
# separator = ""
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
# skip-levels = 1

# [editor.whitespace]
# render = "none"

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"
tabpad = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "."

[editor.soft-wrap]
enable = true

[keys.normal]
H = ":buffer-previous"
L = ":buffer-next"
C-q = ":buffer-close"
C-h = "jump_view_left"
C-l = "jump_view_right"
C-j = "jump_view_down"
C-k = "jump_view_up"
D = ["ensure_selections_forward", "extend_to_line_end"]

